### ISSUE TITLE
Is this solution for "server commands" only?

### ISSUE THREAD

**Issue by ReDev1L** [KyleAMathews/trpc-crdt#6]
How do you overcome this thing:
tables:
users
trpc_calls

you create `trpc call<create user>`, it saves to local and syncs to server.
But, i cant see user in users table yet, before i get sync from server.
so i cant render users table.

Usecase for your implementation is not for every table, just to make some server interactions?

**Comment by KyleAMathews** [comment]
Yes this is only for commands or functions you want to run on the server. E.g. for creating a user, maybe your app has the requirement that before you create a user, you must pull some information from an external account — which you can't do on the client. So creating the user on the server is the best way.

If you haven't, read through my blog post (which expands on the README here) https://bricolage.io/announcing-trpc-crdt/

> Usecase for your implementation is not for every table, just to make some server interactions?

Yes exactly. With local-first, you assume writes will land locally but this library makes it straightforward to move the writes to the server when needed.

**Comment by ReDev1L** [comment]
Thank you very much for response.

And thank you very much for your blog, very interesting thoughts and helpful.
